apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNFekNDQWJxZ0F3SUJBZ0lVTTVicFFTdEJvN2M3Qk5UTlFjdG9qY3JEMjAwd0NnWUlLb1pJemowRUF3SXcKYURFTE1Ba0dBMVVFQmhNQ1ZWTXhGakFVQmdOVkJBZ1REVk5oYmlCR2NtRnVZMmx6WTI4eEN6QUpCZ05WQkFjVApBa05CTVE4d0RRWURWUVFLRXdaRGFXeHBkVzB4RHpBTkJnTlZCQXNUQmtOcGJHbDFiVEVTTUJBR0ExVUVBeE1KClEybHNhWFZ0SUVOQk1CNFhEVEl4TURJd016SXpORGt3TUZvWERUSTJNREl3TWpJek5Ea3dNRm93YURFTE1Ba0cKQTFVRUJoTUNWVk14RmpBVUJnTlZCQWdURFZOaGJpQkdjbUZ1WTJselkyOHhDekFKQmdOVkJBY1RBa05CTVE4dwpEUVlEVlFRS0V3WkRhV3hwZFcweER6QU5CZ05WQkFzVEJrTnBiR2wxYlRFU01CQUdBMVVFQXhNSlEybHNhWFZ0CklFTkJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVQY3BZY1RNUlI3ekVkUVBrcFVtd2xFWTIKTmowU09iMklxUmRPdUJiaWZjOFpHeDUzMEIvR2llb0p2NVZnbDZsNnkyWENkOEZsbktqTExUOG8yQWluN2FOQwpNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGR1R4ClJlZ2ZGVWhCK1NEWFJPS3NyZUkza3hCOE1Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lFSi9VYUprMUdmY1J2aFYKeDE2amxFelpMd2p6TkVuZHdNa0lhU1IvalhtM0FpQmd1MlRXMDhGN01KSnBBVlIwTFF1RTBKcjk3MGFCbGVoWQpjc3NqWUU1RjVRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  ca.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUtrNlFSdXdMNG1MbW95QnBzaVByOFFOVGNUZE1vN0tuU2FMYUVHdHdKSi9vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUGNwWWNUTVJSN3pFZFFQa3BVbXdsRVkyTmowU09iMklxUmRPdUJiaWZjOFpHeDUzMEIvRwppZW9KdjVWZ2w2bDZ5MlhDZDhGbG5LakxMVDhvMkFpbjdRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: "2021-02-03T23:53:40Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:ca.key: {}
      f:type: {}
    manager: cilium
    operation: Update
    time: "2021-02-03T23:53:40Z"
  name: cilium-ca
  namespace: kube-system
  resourceVersion: "3863"
  selfLink: /api/v1/namespaces/kube-system/secrets/cilium-ca
  uid: c9e988fd-11b3-402c-ad75-ba69994aceb7
type: Opaque
